"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
    return queryInterface.bulkInsert(
      "Boats",
      [
        {
          userId: 1,
          address: "Beaver Lake Marina",
          city: "Bentonville",
          state: "AR",
          year: 2022,
          model: "BayLiner",
          description: "Great sound system! Fun for the family and everyone!",
          captain: false,
          price: 500,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 1,
          address: "Beaver Lake Marina",
          city: "Bentonville",
          state: "AR",
          year: 2022,
          model: "BayLiner",
          description: "Coolers, Fishing Poles, Tubes, and Rafts!",
          captain: false,
          price: 500,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 2,
          address: "Beaver Lake Marina",
          city: "Bentonville",
          state: "AR",
          year: 2020,
          model: "Bass Pro",
          description: "Fishing Poles and Live Well Storage",
          captain: false,
          price: 350,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 2,
          address: "Beaver Lake Marina",
          city: "Bentonville",
          state: "AR",
          year: 2009,
          model: "Bass Master",
          description: "Tackle Box",
          captain: false,
          price: 222,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 3,
          address: "Dallas Marina",
          city: "Dallas",
          state: "TX",
          year: 2020,
          model: "Bass Pro",
          description: "Fishing Poles and Live Well Storage",
          captain: false,
          price: 350,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 3,
          address: "Dallas Marina",
          city: "Dallas",
          state: "TX",
          year: 2009,
          model: "Bass Master",
          description: "Tackle Box",
          captain: false,
          price: 222,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 4,
          address: "Portland Marina",
          city: "Portland",
          state: "ME",
          year: 2002,
          model: "Bayliner Deep Sea",
          description: "Deep Sea Fishing Guided Tour",
          captain: true,
          price: 1500,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 4,
          address: "Portland Marina",
          city: "Portland",
          state: "ME",
          year: 2012,
          model: "Luxury Yacht",
          description: "Full Size Kitchen, Master Bedroom, and Bar",
          captain: true,
          price: 1337,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 7,
          address: "New York City Marina",
          city: "New York City",
          state: "NY",
          year: 1911,
          model: "Titanic",
          description: "Full Size Kitchen, Master Bedroom, and Bar",
          captain: true,
          price: 40,
          lat: 37.0902,
          lng: 95.7129,
        },
        {
          userId: 8,
          address: "31 Spooner St",
          city: "Providence",
          state: "RI",
          year: 2020,
          model: "Lil Yachty",
          description: "If you rent this boat Peter and Brian will sing to you the entire time.",
          captain: true,
          price: 500,
          lat: 41.778387,
          lng: -71.421575,
        },
        {
          userId: 16,
          address: "31 Spooner St",
          city: "Daly City",
          state: "CA",
          year: 2018,
          model: "Trimaran",
          description: "Amazing boat to get out on the water in the bay and experience the sunshine.",
          captain: true,
          price: 500,
          lat: 37.693338,
          lng: -122.471506,
        },
        {
          userId: 16,
          address: "12333 W Olympic Blvd",
          city: "Santa Monica",
          state: "CA",
          year: 2018,
          model: "Trawler",
          description:
            "A great boat to get out while you visit Santa Monica.  Make sure to stop by the Riot Game Campus and check out all the cool things they are doing!",
          captain: true,
          price: 500,
          lat: 34.0320487,
          lng: -118.4568894,
        },
        {
          userId: 1,
          address: "12333 W Olympic Blvd",
          city: "Santa Monica",
          state: "CA",
          year: 2018,
          model: "RiotG",
          description:
            "If you happen to be a Riot recruiter and have strolled upon this boat.  I thank you and I hope that we can be in contact soon!",
          captain: true,
          price: 1337,
          lat: 34.0312988,
          lng: -118.4567117,
        },
        {
          userId: 16,
          address: "504 Pacific Ave S",
          city: "Long Beach",
          state: "WA",
          year: 2018,
          model: "Bayliner",
          description: "A nice boat for a weekend get away! ",
          captain: true,
          price: 500,
          lat: 46.3545584,
          lng: -124.0540273,
        },
        {
          userId: 17,
          address: "32302 Historic Columbia River Highway",
          city: "Corbett",
          state: "OR",
          year: 2018,
          model: "Bayliner",
          description: "A nice boat for a weekend get away! ",
          captain: true,
          price: 500,
          lat: 45.5188438,
          lng: -122.3306665,
        },
      ],

      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
    return queryInterface.bulkDelete("Boats", null, {});
  },
};
